(function(g){var window=this;'use strict';var d$a=function(a,b){a.Qa("onAutonavCoundownStarted",b)},j6=function(a,b,c){g.po(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Hf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.NH&&(b.lengthText?(e=b.lengthText||null,f=b.Bt||null):b.lengthSeconds&&(e=g.fN(b.lengthSeconds),f=g.fN(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.LH(d).type;var l=b instanceof g.NH?b.isLivePlayback:null,m=b instanceof g.NH?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],w=[];n&&r.push(n);p&&(r.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.EK("\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.vn(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.Vp};b instanceof g.MH&&(c.playlist_length=b.playlistLength);a.update(c)},k6=function(a){var b=a.V(),c=b.u;
g.V.call(this,{F:"a",K:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.T:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{F:"div",X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},
{F:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"},{F:"div",K:"ytp-autonav-list-overlay",W:[{F:"div",K:"ytp-autonav-mix-text",qa:"\u041c\u0438\u043a\u0441"},{F:"div",K:"ytp-autonav-mix-icon"}]}]},{F:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author",
"ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=null;this.j=c;this.Pa("click",this.onClick);this.Pa("keypress",this.onKeyPress)},l6=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{F:"div",K:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.B=0;this.container=new g.V({F:"div",K:"ytp-autonav-endscreen-countdown-container"});g.M(this,this.container);this.container.Ca(this.element);b=a.V();var d=b.u;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.S(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.N("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.V({F:"div",K:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",K:"ytp-autonav-endscreen-upnext-header"},{F:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{F:"a",K:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.T:""},W:[{F:"div",Ga:e,X:{style:"{{background}}"},W:[{F:"div",
X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{F:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"}]},{F:"div",K:"ytp-autonav-endscreen-video-info",W:[{F:"div",K:"ytp-autonav-endscreen-premium-badge"},{F:"div",K:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{F:"div",K:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},
{F:"div",K:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},{F:"div",K:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.M(this,this.j);this.j.Ca(this.container.element);d||this.S(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.fN);this.G.rb(this.container.element,this,115127);this.G.rb(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({F:"div",K:"ytp-autonav-overlay"});g.M(this,this.overlay);this.overlay.Ca(this.container.element);
this.u=new g.V({F:"div",K:"ytp-autonav-endscreen-button-container"});g.M(this,this.u);this.u.Ca(this.container.element);this.cancelButton=new g.V({F:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
qa:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.M(this,this.cancelButton);this.cancelButton.Ca(this.u.element);this.cancelButton.Pa("click",this.GV,this);this.G.rb(this.cancelButton.element,this,115129);this.playButton=new g.V({F:"a",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
qa:"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438"});g.M(this,this.playButton);this.playButton.Ca(this.u.element);this.playButton.Pa("click",this.fN,this);this.G.rb(this.playButton.element,this,115130);this.C=new g.co(function(){e$a(c)},500);
g.M(this,this.C);this.eN();this.S(a,"autonavvisibility",this.eN);this.G.N("web_autonav_color_transition")&&(this.S(a,"autonavchange",this.FV),this.S(a,"onAutonavCoundownStarted",this.O0))},m6=function(a){var b=a.G.zj(!0,a.G.isFullscreen());
g.po(a.container.element,"ytp-autonav-endscreen-small-mode",a.Cg(b));g.po(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.jF);g.po(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.tf());g.po(a.G.getRootNode(),"countdown-running",a.Fj());g.po(a.container.element,"ytp-player-content",a.G.tf());g.El(a.overlay.element,{width:b.width+"px"});if(!a.Fj()){a.G.tf()?f$a(a,Math.round(g$a(a)/1E3)):f$a(a);b=!!a.suggestion&&!!a.suggestion.Vp;var c=a.G.tf()||!b;
g.po(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.po(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.dM(a.u,a.G.tf());g.po(a.element,"ytp-enable-w2w-color-transitions",h$a(a))}},e$a=function(a){var b=g$a(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);f$a(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Fj()?a.select(!0):a.Fj()&&a.C.start()},g$a=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.EM;return-1===a||void 0===a?8E3:a}return 0<=a.G.rq()?a.G.rq():g.RF(a.G.V().experiments,"autoplay_time")||1E4},h$a=function(a){var b;
return!(null==(b=a.G.getVideoData())||!b.watchToWatchTransitionRenderer)},f$a=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.ah(a);if(0<=b){b=String(b);var c="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.$g("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(0,
d)));var e=g.Zg("span");g.jo(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.fh(e,b);a.appendChild(e);a.appendChild(g.$g("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(d+c.length)));return}}g.fh(a,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")},n6=function(a,b){g.V.call(this,{F:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o6=function(a){g.V.call(this,{F:"div",
Ga:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{F:"div",K:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{F:"span",K:"ytp-upnext-top",W:[{F:"span",K:"ytp-upnext-header",qa:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{F:"span",K:"ytp-upnext-title",qa:"{{title}}"},{F:"span",K:"ytp-upnext-author",qa:"{{author}}"}]},{F:"a",K:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
W:[{F:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},W:[{F:"circle",K:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",K:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",K:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",K:"ytp-upnext-bottom",
W:[{F:"span",K:"ytp-upnext-cancel"},{F:"span",K:"ytp-upnext-paused",qa:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.api=a;this.cancelButton=null;this.D=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.co(this.AC,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=
new g.V({F:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},qa:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.M(this,this.cancelButton);this.cancelButton.Pa("click",this.HV,this);this.cancelButton.Ca(b);this.cancelButton&&this.api.rb(this.cancelButton.element,this,115129);g.M(this,this.C);this.api.rb(this.element,
this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.S(b,"click",this.IV);this.api.rb(b,this,115130);this.gN();this.S(a,"autonavvisibility",this.gN);this.S(a,"mdxnowautoplaying",this.E1);this.S(a,"mdxautoplaycanceled",this.F1);g.po(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},i$a=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.EM;return-1===a||void 0===a?8E3:a}return 0<=a.api.rq()?a.api.rq():g.RF(a.api.V().experiments,"autoplay_time")||1E4},j$a=function(a,b){b=i$a(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Fj()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Fj()&&a.j.start()},p6=function(a){n6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({F:"div",K:"ytp-suggestion-panel",W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0434\u0440\u0443\u0433\u0438\u0435 \u0432\u0438\u0434\u0435\u043e"}]});this.J=new g.V({F:"div",K:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new l6(this.player);g.M(this,this.u);this.u.Ca(this.element);a.getVideoData().Xe?this.j=this.u:
(this.j=new o6(a),g.OO(this.player,this.j.element,4),g.M(this,this.j));this.overlay=new g.V({F:"div",K:"ytp-autonav-overlay-cancelled-state"});g.M(this,this.overlay);this.overlay.Ca(this.element);this.C=new g.QE(this);g.M(this,this.C);g.M(this,this.table);this.table.Ca(this.element);this.table.show();g.M(this,this.J);this.J.Ca(this.table.element);this.hide()},q6=function(a){var b=a.tf();
b!==a.D&&(a.D=b,a.player.ma("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},r6=function(a,b){g.V.call(this,{F:"button",
Ga:["ytp-watch-on-youtube-button","ytp-button"],X:{title:"{{message}}"},qa:"{{content}}"});this.G=a;this.buttonType=this.buttonType=b;switch(this.buttonType){case 1:a="\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c \u0441\u043d\u043e\u0432\u0430 \u043d\u0430 YouTube";b=156915;break;case 2:a="\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043d\u0430 YouTube";b=156942;break;default:a="\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043d\u0430 YouTube",
b=156942}this.update({message:a,content:a});this.G.rb(this.element,this,b);this.Pa("click",this.onClick);g.dM(this,!0)},s6=function(a,b){n6.call(this,a,"embeds-lite-endscreen");
this.G=a;this.j=b;this.G.rb(this.element,this,156943);this.watchButton=new r6(a,2);g.M(this,this.watchButton);this.watchButton.Ca(this.element);this.hide()},k$a=function(a){n6.call(this,a,"subscribecard-endscreen");
this.j=new g.V({F:"div",K:"ytp-subscribe-card",W:[{F:"img",K:"ytp-author-image",X:{src:"{{profilePicture}}"}},{F:"div",K:"ytp-subscribe-card-right",W:[{F:"div",K:"ytp-author-name",qa:"{{author}}"},{F:"div",K:"html5-subscribe-button-container"}]}]});g.M(this,this.j);this.j.Ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.yQ("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",
null,!0,!1,b.al,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.subscribeButton);this.subscribeButton.Ca(this.j.Da("html5-subscribe-button-container"));this.S(a,"videodatachange",this.La);this.La();this.hide()},t6=function(a){var b=a.V(),c=g.TE||g.HG?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.V.call(this,{F:"a",Ga:e,X:{href:"{{url}}",target:d?b.T:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{F:"div",K:"ytp-videowall-still-image",X:{style:"{{background}}"}},{F:"span",K:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{F:"span",K:"ytp-videowall-still-info-bg",W:[{F:"span",K:"ytp-videowall-still-info-content",X:c,W:[{F:"span",K:"ytp-videowall-still-info-title",
qa:"{{title}}"},{F:"span",K:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{F:"span",K:"ytp-videowall-still-info-live",qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{F:"span",K:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{F:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{F:"span",K:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{F:"span",K:"ytp-videowall-still-listlabel-length",
W:[" (",{F:"span",qa:"{{playlist_length}}"},")"]}]},{F:"span",Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{F:"span",K:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{F:"span",K:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.QE(this);g.M(this,this.j);this.Pa("click",this.onClick);this.Pa("keypress",this.onKeyPress);this.j.S(a,"videodatachange",this.onVideoDataChange);
a.yg(this.element,this);this.onVideoDataChange()},u6=function(a){n6.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.T=null;this.u=new g.QE(this);g.M(this,this.u);this.Y=a.N("web_rounded_thumbnails");this.I=new g.co(function(){g.lo(b.element,"ytp-show-tiles")},0);
g.M(this,this.I);var c=new g.V({F:"button",Ga:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},W:[g.iM()]});g.M(this,c);c.Ca(this.element);c.Pa("click",this.MV,this);this.table=new g.aM({F:"div",K:"ytp-endscreen-content"});g.M(this,this.table);this.table.Ca(this.element);c=new g.V({F:"button",Ga:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},W:[g.jM()]});g.M(this,c);c.Ca(this.element);c.Pa("click",
this.LV,this);a.getVideoData().Xe?this.j=new l6(a,!0):this.j=new o6(a);g.M(this,this.j);g.OO(this.player,this.j.element,4);a.rb(this.element,this,158789);this.hide()},v6=function(a){return g.PO(a.player)&&a.Ky()&&!a.C},l$a=function(a){var b,c,d,e;
return(null==(b=a.videoData)?0:null==(c=b.suggestions)?0:c.length)?null==(d=a.videoData)?void 0:d.suggestions:[null==(e=a.videoData)?void 0:g.NI(e)]},w6=function(a){var b=a.tf();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},x6=function(a){n6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r6(a,1);g.M(this,this.watchButton);this.watchButton.Ca(this.element);g.C1a(a)&&(this.j=new g.t2(a,g.lO(a)),g.M(this,this.j),this.u=new g.V({F:"div",Ga:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[this.j]}),g.M(this,this.u),this.j.Ca(this.u.element),this.u.Ca(this.element));a.rb(this.element,this,156914);this.hide()},p$a=function(a){g.vP.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.QE(this);g.M(this,this.listeners);var c=a.V(),d=a.getVideoData();d=d&&0!==d.endSeconds;if(g.Bv(g.bH(c))&&d&&!g.LO(a))this.u=!0,this.endScreen=new s6(a,g.lO(a));else{var e;(null==(e=g.lO(a))?0:e.Ej())?this.endScreen=new x6(a):m$a(a)?(this.C=!0,n$a(this),this.j?this.endScreen=new p6(a):this.endScreen=new u6(a)):c.Sf?this.endScreen=new k$a(a):this.endScreen=new n6(a)}g.M(this,this.endScreen);g.OO(a,this.endScreen.element,
4);o$a(this);this.listeners.S(a,"videodatachange",this.onVideoDataChange,this);this.listeners.S(a,g.ZA("endscreen"),function(f){b.onCueRangeEnter(f)});
this.listeners.S(a,g.$A("endscreen"),function(f){b.onCueRangeExit(f)})},n$a=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.jl&&a.B===b.Xe)return!1;a.j=b.jl;a.B=b.Xe;return!0},m$a=function(a){a=a.V();
return a.Yc&&!a.Sf},o$a=function(a){a.player.Df("endscreen");
var b=a.player.getVideoData();b=new g.XA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.XA(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.xe([b,c])};
g.zT.prototype.ox=g.ba(35,function(a){this.JK!==a&&(this.JK=a,this.bk())});
g.yT.prototype.Dp=g.ba(34,function(a){this.u!==a&&(this.u=a,this.By())});
g.zT.prototype.Dp=g.ba(33,function(a){this.fl&&this.fl.Dp(a)});
g.kQ.prototype.bB=g.ba(32,function(a){this.KK!==a&&(this.KK=a,this.Wn())});
g.EO.prototype.rq=g.ba(6,function(){return this.app.rq()});
g.kZ.prototype.rq=g.ba(5,function(){return this.getVideoData().YM});g.v(k6,g.V);k6.prototype.select=function(){this.G.xm(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.gz||void 0)&&this.G.tb(this.element)};
k6.prototype.onClick=function(a){g.WP(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Sx(a)||(this.select(),g.Rx(a))}};g.v(l6,g.V);g.k=l6.prototype;g.k.KB=function(a){this.suggestion!==a&&(this.suggestion=a,j6(this.j,a),this.playButton.updateValue("url",this.suggestion.vn()),m6(this))};
g.k.Fj=function(){return 0<this.B};
g.k.xx=function(){this.Fj()||(this.B=Date.now(),e$a(this),d$a(this.G,g$a(this)),g.po(this.G.getRootNode(),"countdown-running",this.Fj()))};
g.k.Nt=function(){this.Gp();e$a(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.fh(a,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")};
g.k.Gp=function(){this.Fj()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.Gp()};
g.k.fN=function(a){g.WP(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.tb(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.G.Va(a,!0),this.G.tb(a)),this.select())};
g.k.GV=function(){this.G.tb(this.cancelButton.element);g.JO(this.G,!0);this.D&&this.G.Qa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.CX)?void 0:c.command};
g.k.O0=function(a){if(h$a(this)){var b=this.G.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.qN(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.qN(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.qN(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.qN(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.qN(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.qN(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.po(this.element,"ytp-w2w-animate",!0)}};
g.k.FV=function(a){this.G.N("web_autonav_color_transition")&&2!==a&&g.po(this.element,"ytp-w2w-animate",!1)};
g.k.eN=function(){var a=this.G.tf();this.I&&this.sb!==a&&g.dM(this,a);m6(this);this.G.Va(this.container.element,a);this.G.Va(this.cancelButton.element,a);this.G.Va(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.G.Va(this.playButton.element,a)};
g.k.Cg=function(a){return 400>a.width||459>a.height};g.v(n6,g.V);g.k=n6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Ky=function(){return!1};
g.k.tf=function(){return!1};
g.k.XQ=function(){return!1};g.v(o6,g.V);g.k=o6.prototype;g.k.AC=function(){this.notification&&(this.C.stop(),this.zc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.KB=function(a){this.suggestion=a;j6(this,a,"hqdefault.jpg")};
g.k.gN=function(){g.dM(this,this.api.tf());this.api.Va(this.element,this.api.tf());this.api.Va(this.Da("ytp-upnext-autoplay-icon"),this.api.tf());this.cancelButton&&this.api.Va(this.cancelButton.element,this.api.tf())};
g.k.N1=function(){window.focus();this.AC()};
g.k.xx=function(a){var b=this;this.Fj()||(g.gy("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+this.suggestion.title),this.u=(0,g.Q)(),this.j=new g.co(function(){j$a(b,a)},25),j$a(this,a),d$a(this.api,i$a(this,a)));
g.no(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Fj=function(){return!!this.j};
g.k.Nt=function(){this.Gp();this.u=(0,g.Q)();j$a(this);g.lo(this.element,"ytp-upnext-autoplay-paused")};
g.k.Gp=function(){this.Fj()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.AC(),this.notification=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:this.suggestion.title,icon:this.suggestion.Hf()}),this.B=this.S(this.notification,"click",this.N1),this.C.start())}this.Gp();this.api.nextVideo(!1,
a)};
g.k.IV=function(a){!g.eh(this.cancelButton.element,g.Cx(a))&&g.WP(a,this.api)&&(this.api.tf()&&this.api.tb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.HV=function(){this.api.tf()&&this.cancelButton&&this.api.tb(this.cancelButton.element);g.JO(this.api,!0)};
g.k.E1=function(a){this.api.getPresentingPlayerType();this.show();this.xx(a)};
g.k.F1=function(){this.api.getPresentingPlayerType();this.Gp();this.hide()};
g.k.ra=function(){this.Gp();this.AC();g.V.prototype.ra.call(this)};g.v(p6,n6);g.k=p6.prototype;g.k.create=function(){n6.prototype.create.call(this);this.C.S(this.player,"appresize",this.ey);this.C.S(this.player,"onVideoAreaChange",this.ey);this.C.S(this.player,"videodatachange",this.onVideoDataChange);this.C.S(this.player,"autonavchange",this.hN);this.C.S(this.player,"autonavcancel",this.JV);this.onVideoDataChange()};
g.k.show=function(){n6.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.JO(this.player,!1);g.PO(this.player)&&this.Ky()&&!this.B?(q6(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.xx():3===this.videoData.autonavState&&this.j.Nt()):(g.JO(this.player,!0),q6(this));this.ey()};
g.k.hide=function(){n6.prototype.hide.call(this);this.j.Nt();q6(this)};
g.k.ey=function(){var a=this.player.zj(!0,this.player.isFullscreen());q6(this);m6(this.u);g.po(this.element,"ytp-autonav-cancelled-small-mode",this.Cg(a));g.po(this.element,"ytp-autonav-cancelled-tiny-mode",this.ND(a));g.po(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.El(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.t(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.t(b.value);b=c.next().value;c=c.next().value;g.po(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.NI(this.videoData);b&&(this.j.KB(b),this.j!==this.u&&this.u.KB(b));for(b=0;b<q$a.length;++b){var c=q$a[b];if(a&&a[c]){this.videos[b]=new k6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j6(d,c));g.M(this,this.videos[b]);this.videos[b].Ca(this.J.element)}}}this.ey()}};
g.k.hN=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Gp(),this.sb&&this.ey()):(this.I=!0,this.tf()&&(2===a?this.j.xx():3===a&&this.j.Nt()))};
g.k.JV=function(a){a?this.hN(1):(this.B=null,this.I=!1)};
g.k.Ky=function(){return 1!==this.videoData.autonavState};
g.k.Cg=function(a){return(910>a.width||459>a.height)&&!this.ND(a)&&!(400>=a.width||360>=a.height)};
g.k.ND=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.tf=function(){return this.sb&&g.PO(this.player)&&this.Ky()&&!this.B};
var q$a=[1,3,2,4];g.v(r6,g.V);g.k=r6.prototype;g.k.onClick=function(a){g.XP(this.getVideoUrl(),this.G,a);this.G.tb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.G.getVideoUrl(a,!1,!1,!0);var b=this.G.V();if(g.JG(b)||g.TG(b)){var c={};b.Aa&&g.JG(b)&&g.XN(c,b.loaderUrl);g.JG(b)&&g.hO(this.G,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.WN(c,b);a=g.ii(a,c)}return a};
g.k.Va=function(){this.G.Va(this.element,this.sb&&this.ya)};
g.k.show=function(){g.V.prototype.show.call(this);this.Va()};
g.k.hide=function(){g.V.prototype.hide.call(this);this.Va()};
g.k.Wb=function(a){g.V.prototype.Wb.call(this,a);this.Va()};g.v(s6,n6);s6.prototype.show=function(){3!==this.player.getPlayerState()&&(n6.prototype.show.call(this),this.j.ox(!0),this.j.Dp(!0),this.G.Va(this.element,!0),this.watchButton.Wb(!0))};
s6.prototype.hide=function(){n6.prototype.hide.call(this);this.j.ox(!1);this.j.Dp(!1);this.G.Va(this.element,!1);this.watchButton.Wb(!1)};g.v(k$a,n6);k$a.prototype.La=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.al;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.v(t6,g.V);t6.prototype.select=function(){this.api.xm(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.gz||void 0)&&this.api.tb(this.element)};
t6.prototype.onClick=function(a){g.WP(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
t6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Sx(a)||(this.select(),g.Rx(a))}};
t6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.u};g.v(u6,n6);g.k=u6.prototype;g.k.create=function(){n6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.po();this.u.S(this.player,"appresize",this.po);this.u.S(this.player,"onVideoAreaChange",this.po);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.u.S(this.player,"autonavchange",this.bG);this.u.S(this.player,"autonavcancel",this.KV);a=this.videoData.autonavState;a!==this.T&&this.bG(a);this.u.S(this.element,"transitionend",this.m3)};
g.k.destroy=function(){g.Hz(this.u);g.Xe(this.stills);this.stills=[];n6.prototype.destroy.call(this);g.no(this.element,"ytp-show-tiles");this.I.stop();this.T=this.videoData.autonavState};
g.k.Ky=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.sb;n6.prototype.show.call(this);l$a(this);g.no(this.element,"ytp-show-tiles");this.player.V().isMobile?g.fo(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.JO(this.player,!1);v6(this)?(w6(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.xx():3===this.videoData.autonavState&&this.j.Nt()):(g.JO(this.player,!0),w6(this));a!==this.sb&&
this.player.Va(this.element,!0)};
g.k.hide=function(){var a=this.sb;n6.prototype.hide.call(this);this.j.Nt();w6(this);a!==this.sb&&this.player.Va(this.element,!1)};
g.k.m3=function(a){g.Cx(a)===this.element&&this.po()};
g.k.po=function(){var a=l$a(this);if(a.length){g.lo(this.element,"ytp-endscreen-paginate");var b=this.G.zj(!0,this.G.isFullscreen()),c=g.lO(this.G);c&&(c=c.If()?48:32,b.width-=2*c);var d=b.width/b.height,e=96/54,f=c=2,h=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=a.length,n=Math.pow(2,2);var p=m*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-n;for(p-=n;0<p&&(c<h||f<l);){var q=c/2,r=f/2,w=c<=h-2&&p>=r*n,y=f<=l-2&&p>=q*n;if((q+1)/r*e/d>d/(q/(r+1)*e)&&y)p-=q*n,f+=2;else if(w)p-=r*n,c+=2;else if(y)p-=q*
n,f+=2;else break}e=!1;p>=3*n&&6>=m*n-p&&(4<=f||4<=c)&&(e=!0);n=96*c;p=54*f;d=n/p<d?b.height/p:b.width/n;d=Math.min(d,2);n=Math.floor(Math.min(b.width,n*d));p=Math.floor(Math.min(b.height,p*d));b=this.table.element;b.ariaLive="polite";g.Ol(b,n,p);g.El(b,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.KB(g.NI(this.videoData));this.j instanceof l6&&m6(this.j);g.po(this.element,"ytp-endscreen-takeover",v6(this));w6(this);n+=4;p+=4;d=0;b.ariaBusy="true";for(h=0;h<c;h++)for(l=0;l<f;l++)if(q=d,w=0,e&&
h>=c-2&&l>=f-2?w=1:0===l%2&&0===h%2&&(2>l&&2>h?0===l&&0===h&&(w=2):w=2),q=g.yg(q+this.B,m),0!==w){r=this.stills[d];r||(r=new t6(this.player),this.stills[d]=r,b.appendChild(r.element));y=Math.floor(p*l/f);var z=Math.floor(n*h/c),B=Math.floor(p*(l+w)/f)-y-4,D=Math.floor(n*(h+w)/c)-z-4;g.Kl(r.element,z,y);g.Ol(r.element,D,B);g.El(r.element,"transitionDelay",(l+h)/20+"s");g.po(r.element,"ytp-videowall-still-mini",1===w);g.po(r.element,"ytp-videowall-still-large",2<w);this.Y&&(w=Math.max(D,B),g.po(r.element,
"ytp-videowall-still-round-large",256<=w),g.po(r.element,"ytp-videowall-still-round-medium",96<w&&256>w),g.po(r.element,"ytp-videowall-still-round-small",96>=w));q=a[q];r.suggestion!==q&&(r.suggestion=q,w=r.api.V(),y=g.ko(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j6(r,q,y),g.JG(w)&&(y=q.vn(),z={},w.Aa&&g.XN(z,w.loaderUrl),g.hO(r.api,"addEmbedsConversionTrackingParams",[z]),y=g.ii(y,g.WN(z,"emb_rel_end")),r.updateValue("url",y)),(q=(q=q.sessionData)&&q.itct)&&r.api.Ah(r.element,
q));d++}b.ariaBusy="false";g.po(this.element,"ytp-endscreen-paginate",d<m);for(a=this.stills.length-1;a>=d;a--)c=this.stills[a],g.ch(c.element),g.We(c);this.stills.length=d}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.po())};
g.k.LV=function(){this.B+=this.stills.length;this.po()};
g.k.MV=function(){this.B-=this.stills.length;this.po()};
g.k.XQ=function(){return this.j.Fj()};
g.k.bG=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Gp(),this.sb&&this.po()):(this.D=!0,this.sb&&v6(this)&&(2===a?this.j.xx():3===a&&this.j.Nt()))};
g.k.KV=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Va(this.stills[a].element,!0);this.bG(1)}else this.C=null,this.D=!1;this.po()};
g.k.tf=function(){return this.sb&&v6(this)};g.v(x6,n6);x6.prototype.show=function(){if(3!==this.player.getPlayerState()){n6.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.po(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.lO(this.player))||c.bB(!0);this.player.Va(this.element,!0);this.watchButton.Wb(!0)}};
x6.prototype.hide=function(){n6.prototype.hide.call(this);var a;null==(a=g.lO(this.player))||a.bB(!1);this.player.Va(this.element,!1);this.watchButton.Wb(!1)};g.v(p$a,g.vP);g.k=p$a.prototype;g.k.ju=function(){var a;if((null==(a=g.lO(this.player))?0:a.Ej())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.NI(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!m$a(this.player)||c;c=a.Ri||g.TG(a.u);var d=this.player.pz();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.tf=function(){return this.endScreen.tf()};
g.k.z_=function(){return this.tf()?this.endScreen.XQ():!1};
g.k.ra=function(){this.player.Df("endscreen");g.vP.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.vb().Ie.get("heartbeat"),d=g.NI(a);!d||b.videoId!==d.videoId||a.hR?(this.player.xm(b.videoId,void 0,void 0,!0,!0,b),c&&c.TD("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.vP.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.vP.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.ju()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){o$a(this);this.C&&n$a(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p6(this.player):this.endScreen=new u6(this.player),g.M(this,this.endScreen),g.OO(this.player,this.endScreen.element,4))};g.uP("endscreen",p$a);})(_yt_player);
